defaults:
  - model: se-itm-net
  - dataset: cai_mef
  - optimizer: adam
  - lr_scheduler: multi_step
seed: null
epoch: 100
loader: 
  batch_size: 16
  num_workers: 0
test:
  result_path: ./result/
